.TH PIXAM 1 "30 Jul 2019" "0.0.89" "User Manual"

.SH NAME
pixam \- Pixel Art Maker

.SH SYNOPSIS
.B pixam
.RB command
.RB options
.br
.B pixam palette
.RB image.png
.RB colorsCount
[
.I output.png
]
.br
.B pixam dither
.RB image.png
.RB palette.png
.RB pattern.png
[
.I output.png
]
.br
.B pixam undither
.RB image.png
.RB pattern.png
[
.I output.png
]
.br
.B pixam unditherscan
.RB image.png
.RB pattern.png
[
.I output.png
]

.SH DESCRIPTION
.I pixam
generate palettes and dither any image with personal patterns.

.SH OPTIONS
.TP
.B image.png
path to the image file to dither (support CImg, recommends PNG)
.TP
.B palette.png
path to the palette file.
.TP
.B pattern.png
path to the image to use as a dithering pattern
.TP
.B colorsCount
desired number of colors in the palette used
.TP
.I output.png
result image
.br
default for
.I palette
:
.br
palette-<colorCount>-<image>.png
.br
default for
.I dither
:
.br
<image>-dithered-by-<pattern>-with-<palette>.png
.br
default for
.I undither | unditherscan
:
.br
<image>-undithered-by-<pattern>.png

.SH "SEE ALSO"
pngnq(1), pngquant(1), gm(1)

.SH COPYRIGHT
Copyright \(co 2014 Nicolas Gaborit <hello@soreine.dev>
.br
Public Domain Mark 1.0
.br
No Copyright
